### ISSUE TITLE
tab icon

### ISSUE THREAD

**Issue by mfoucht** [ianjwhitmore/ecotrust-northwest-community-forests#24] opened 2017-12-14 17:47 UTC
This is a small issue, but definitely interested in switching up the icon on the tab to the branch when you get a chance. Currently the yellow Ollo theme icon

**Comment by ianjwhitmore** [comment] 2017-12-14 17:53
@hbdelacruz is working on this currently. Duplicate of #6

**Closed** 2017-12-14 17:53 UTC
